language: java
jdk: openjdk8
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: scFHONZvn5pCGapg0iydUmsC98uUuGrKT4Yn40EKUwitFBrh4D/p+uhdppBIy1d0PbTM+fELFJ2uHHxfuybGC3zlcbRXISBVj8BYBpz3czW17Nb/+XeeqDrGwwDYxZSuzqkE3oJ+anz6CROEoAMqCOcpvOzP07nB5JGOspvU/qnjo4d7TznEdMBd85T7PFWP269FEMkulqapQskMN+W7QA03Vh6cJlj2rNtyV1zVAcs6TvRtTCIyBXaWZEYWT6umdinJlwql6LXoWtWCCHA2j/hHtXQpfgD7VXHblLo3hjl6vcFWUEMkDzmcYTPwSKrzjGUt+i5pUOu3uo8l9VOX6iskzSzg5ADkzWWLID7LgV7UbHrGpLOZI867DGCFGYpRc9AuhCSTaa/VmtONiRbfbmCrYjWmn+1lA/MulsK9IFt1mLVWJBkig6u3hNIMWc440H7gl1T1Ox9b8IqinkQXIU5xJ4KinxTwDs5LabVmrBvPkfpvw1jUpQdKpKeC/Dfu1HNrAeVvZuKG1k+hViOa426mmwt++BkyVD6nP0pD90pF/RQ9KYE2fmqmyfX7QS3FwR4clqiaL4lwpaUtrK+PE0ioLQ0pESHNlvNwESUj5gkY92sxuc5oN7hZ42lWXo5fTnVqB2flEiOMalFISPz/rYZf95a3zNqU0ZB+K0GjkwM=
app: ts-fas
